version: '3.8'

services:
  api:
    image: datascientest/fastapi:1.0.0
    container_name: fastapi_container
    networks:
      - test_network

  test_authentication:
    build:
      context: .
      dockerfile: Dockerfile.test_authentication
    container_name: test_authentication_container
    environment:
      - LOG=1
      - API_ADDRESS=api
      - API_PORT=8000
    depends_on:
      - api
    networks:
      - test_network
    volumes:
      - ./logs:/app/logs

  test_authorization:
    build:
      context: .
      dockerfile: Dockerfile.test_authorization
    container_name: test_authorization_container
    environment:
      - LOG=1
      - API_ADDRESS=api
      - API_PORT=8000
    depends_on:
      - api
    networks:
      - test_network
    volumes:
      - ./logs:/app/logs

  test_content:
    build:
      context: .
      dockerfile: Dockerfile.test_content
    container_name: test_content_container
    environment:
      - LOG=1
      - API_ADDRESS=api
      - API_PORT=8000
    depends_on:
      - api
    networks:
      - test_network
    volumes:
      - ./logs:/app/logs

  summary:
    image: python:3.9-slim
    container_name: summary_container
    depends_on:
      - test_authentication
      - test_authorization
      - test_content
    volumes:
      - ./logs:/app/logs
      - ./summary.py:/app/summary.py
    command: >
      sh -c "sleep 10 && python /app/summary.py"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge