FROM python:3.9-slim

WORKDIR /app
# Create the logs directory
RUN mkdir -p /app/logs

COPY . /app

RUN pip install --upgrade pip --no-cache-dir --progress-bar off
RUN pip install -r requirements.txt --no-cache-dir --progress-bar off

#CMD ["python", "test_content.py"]
CMD sh -c "python test_authentication.py && sleep 10"