# Base image
# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy application files
COPY . /app

# Upgrade pip and install requests, disabling progress bars to save resources
RUN pip install --upgrade pip --no-cache-dir --progress-bar off
RUN pip install -r requirements.txt --no-cache-dir --progress-bar off

# Set the command to run your script and keep the container alive
CMD sh -c "python test_authentication.py && sleep 10"


